apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
      - name: my-container
        image: eu.gcr.io/$PROJECT_ID/my-app:$COMMIT_SHA
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080